T11/admin insert data view
burtonjong/spreadsheet-planner pull request #18
Opened 2024-07-02 03:44 UTC by promatty

The admin panel, which allows AdminUser members to choose Users from the database, and add Sessions to them.

2024-07-02 23:52 UTC, burtonjong commented on src/components/admin/AdminForm.tsx
> +  useEffect(() => {
use tanstack

2024-07-03 00:12 UTC, burtonjong requested changes

2024-07-03 00:12 UTC, burtonjong commented on src/components/admin/AdminForm.tsx
> +  useEffect(() => {
use tanstack

2024-07-03 00:12 UTC, burtonjong commented on src/components/admin/AdminForm.tsx
> +          <form
please just use tailwind

2024-07-03 00:12 UTC, burtonjong commented on src/components/admin/AdminForm.tsx
> +            <div style={{ marginBottom: "10px" }}>
tailwind

2024-07-03 00:12 UTC, burtonjong commented on src/components/admin/AdminForm.tsx
> +import { useForm } from "react-hook-form";
fix eslint error here

2024-07-03 00:12 UTC, burtonjong commented on src/components/Header.tsx
> +      (route) => route.name != "Admin Panel",
fix eslint

2024-07-03 01:52 UTC, promatty commented
hit me with a "lgtm" for a cookie :)

2024-07-03 02:09 UTC, burtonjong approved these changes

2024-07-03 02:11 UTC, burtonjong commented
lgtm just had to deal with merge conflicts as long as eslint passes

2024-07-03 03:31 UTC, promatty commented
YIPPEE!!!!

2024-07-03 03:31 UTC, merged